# fly.toml app configuration file generated for rotombot on 2025-03-20T02:27:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rotombot'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[services.http_checks]]
interval = "4m" #vérifie toutes les 4 minutes
grace_period = "10s"
method = "GET"
path = "/"
protocol = "https"
timeout = "2s"